In [6]:
import pandas as pd

df = pd.read_csv("dataset/diamonds.csv", index_col=0)
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
df["cut"].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [7]:
cut_class_dict = {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}
clarity_dict = {"I3": 1, "I2": 2, "I1": 3, "SI2": 4, "SI1": 5, "VS2": 6, "VS1": 7, "VVS2": 8, "VVS1": 9, "IF": 10, "FL": 11}
color_dict = {"J": 1,"I": 2,"H": 3,"G": 4,"F": 5,"E": 6,"D": 7}

df["cut"] = df["cut"].map(cut_class_dict)
df["clarity"] = df["clarity"].map(clarity_dict)
df["color"] = df["color"].map(color_dict)

df.head()

   carat  cut  color  clarity  depth  table  price     x     y     z
1   0.23    5      6        4   61.5   55.0    326  3.95  3.98  2.43
2   0.21    4      6        5   59.8   61.0    326  3.89  3.84  2.31
3   0.23    2      6        7   56.9   65.0    327  4.05  4.07  2.31
4   0.29    4      2        6   62.4   58.0    334  4.20  4.23  2.63
5   0.31    2      1        4   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
import sklearn
from sklearn import svm, preprocessing

df = sklearn.utils.shuffle(df)

X = df.drop("price", axis=1).values
X = preprocessing.scale(X)
y = df["price"].values

test_size = 200

X_train = X[:-test_size]
y_train = y[:-test_size]

X_test = X[-test_size:]
y_test = y[-test_size:]

clf = svm.SVR(kernel="linear")
clf.fit(X_train, y_train)

In [9]:
clf.score(X_test, y_test)

array([[0.79, 5.  , 4.  , ..., 5.98, 6.02, 3.62],
       [1.54, 1.  , 6.  , ..., 7.28, 7.22, 4.69],
       [0.3 , 5.  , 6.  , ..., 4.39, 4.36, 2.64],
       ...,
       [0.31, 4.  , 4.  , ..., 4.47, 4.42, 2.58],
       [1.21, 4.  , 2.  , ..., 6.94, 6.91, 4.15],
       [0.78, 3.  , 3.  , ..., 5.82, 5.86, 3.71]])